" === Vundle Setup ===
" ====================
set nocompatible
filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" === Plugins ===

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on
" === End Vundle Setup ===
" ========================

" mouse
set mouse=a
set ttymouse=xterm2

" Line numbers
set number

" turn on syntax highlighting
syntax on

"Reload files changed outside vim
set autoread

" languague dependent indenting
" filetype detection
filetype plugin indent on

" wrapping
set wrap
" break line at words
set linebreak

" === Search Settings ===

" Find next match as we type the search
set incsearch

" Highlight searches
" :noh to remove highlighting.
set hlsearch

" maps \<space> to :noh
nnoremap <leader><space> :noh<cr>

" smart case-insensitive searching
set ignorecase
set smartcase

" === Swap files ===
set directory=/tmp
set backupdir=/tmp

" colorscheme
colorscheme desert
set background=dark

" max 80 characters
set textwidth=80
set formatoptions=tcq

" Whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWritePre * :%s/\s\+$//e

" === Others ===
set modelines=0
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set undofile
set undodir=$HOME/.vim/undo

