" === Vundle Setup ===
" ====================
set nocompatible
filetype off
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" === Plugins ===
Plugin 'altercation/vim-colors-solarized'   " solarized
Plugin 'tomtom/tcomment_vim'                " gcc for comments.
Plugin 'scrooloose/syntastic'
Plugin 'ervandew/supertab'
" Plugin 'SirVer/ultisnips'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sleuth'
Plugin 'bling/vim-airline'
Plugin 'sheerun/vim-polyglot'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'jremmen/vim-ripgrep'
Plugin 'peitalin/vim-jsx-typescript'
Plugin 'neoclide/coc.nvim'
Plugin 'yssl/QFEnter'

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on
" On pressing tab, insert 2 spaces
set expandtab
" show existing tab with 2 spaces width
set tabstop=2
set softtabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2
" === End Vundle Setup ===
" ========================
"
let g:polyglot_disabled = ['typescript']
" let g:rg_derive_root = 1

" Most comments from: http://dougblack.io/words/a-good-vimrc.html
syntax on       " enable syntax highlighting
set number      " line numbers
set showcmd     " show command in bottom bar
set cursorline  " highlight current line
set lazyredraw  " redraw only when we need to
set showmatch   " highlight matching parenthesis/brackets etc
set wrap        " wrapping
set linebreak   " break line at words
set autoread    "Reload files changed outside vim
set autoindent  " copies the indentation from the previous line.
set showmode    " shows the current mode at the bottom of vim.
set visualbell  " vim flashes its scren instead of sounding a beep.
set ttyfast     " tell vim that the terminal is fast.
set ruler       " show line, column numbers in the status line.
set backspace=indent,eol,start " this makes backspace work like normal
set laststatus=2    " Shows current file in the status line.
set relativenumber " Show relative line numbers.

" Wildmenu
set wildmenu                    " visual autocomplete for command menu
set wildmode=list:longest,full  " Controls the behavior of the wildmenu.

" Mouse
set mouse=a             " mouse enabled for all.
set ttymouse=xterm2     " I used iterm2.

" Search stuff.
set incsearch   " search as characters are entered
set hlsearch    " highlight matches
set ignorecase  " case-insensitive searching
set smartcase   " smart case searching
set scrolloff=5 " number of context lines before search result.
" maps \<space> to :noh
nnoremap <leader><space> :noh<cr>

" Folding.
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
set foldmethod=indent   " fold based on indent level
nnoremap <space> za     " space opens/closes folds

" Movement
" nnoremap j gj   " move vertically by visual line
" nnoremap k gk   " move vertically by visual line

" Backups/undo
set backup
set undofile
set writebackup
set backupdir=/tmp
set directory=/tmp
set undodir=/tmp

" colorscheme
colorscheme solarized
set background=dark

set textwidth=80    " max 80 characters
" == formatoptions options.
" t - textwidth
" c - comments (plus leader -- see :help comments)
" q - allogw 'gq' to work
" n - numbered lists
" 2 - keep second line indent
" 1 - single letter words on next line
" r - (in mail) comment leader after
set formatoptions=tcq

" Whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWritePre * :%s/\s\+$//e

" Others
" =====
" When opening a new file and current buffer has unsaved changes, cause files to
" hidden instead of closed.
set hidden
set encoding=utf-8

" vim-airline arrors.
let g:airline_powerline_fonts = 1

set splitright

" bind F to grep word under cursor
" set grepprg=grep\ -nsRIH\ --exclude-dir=types\ --exclude-dir=sub_modules\ --exclude-dir=node_modules\ --exclude-dir=build
nnoremap F :Rg "<C-R><C-W>" <CR>
" command! -bang -nargs=* GGrep
"   \ call fzf#vim#grep(
"   \   'git grep --line-number '.shellescape(<q-args>), 0,
"   \   { 'dir': systemlist('git rev-parse --show-toplevel')[0] }, <bang>0)
"
nnoremap <c-p> :FZF<cr>
let g:fzf_action = {
      \ 'ctrl-s': 'split',
      \ 'ctrl-v': 'vsplit'
      \ }
