#!/usr/bin/env ruby

git_bundles = %w{
  git://github.com/groenewege/vim-less.git
  git://github.com/elzr/vim-json.git
  git://github.com/kchmck/vim-coffee-script.git
  git://github.com/pangloss/vim-javascript.git
  git://github.com/scrooloose/nerdtree.git
  git://github.com/tomtom/tcomment_vim.git
  git://github.com/tpope/vim-haml.git
  git://github.com/tpope/vim-markdown.git
  git://github.com/tpope/vim-rails.git
  git://github.com/tpope/vim-surround.git
  git://github.com/tpope/vim-vividchalk.git
  git://github.com/tsaleh/vim-matchit.git
  git://github.com/vim-ruby/vim-ruby.git
  git://github.com/vim-scripts/jQuery.git
  git://github.com/nathanaelkane/vim-indent-guides.git

  # snipmate & deps
  git://github.com/garbas/vim-snipmate.git
  https://github.com/tomtom/tlib_vim.git
  https://github.com/MarcWeber/vim-addon-mw-utils.git
  https://github.com/honza/snipmate-snippets.git

  https://github.com/ciaranm/detectindent.git
  https://github.com/Raimondi/delimitMate.git
  git://github.com/digitaltoad/vim-jade.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

